import type { GlyphTemplateDefinition } from "./types";

export const horizontalGlyphs = [
  {
    id: "a",
    kana: "あ",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/a.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: false,
    supportsHandakuten: false,
    supportsSmallForm: true,
  },
  {
    id: "i",
    kana: "い",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/i.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: false,
    supportsHandakuten: false,
    supportsSmallForm: true,
  },
  {
    id: "u",
    kana: "う",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/u.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: false,
    supportsHandakuten: false,
    supportsSmallForm: true,
  },
  {
    id: "e",
    kana: "え",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/e.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: false,
    supportsHandakuten: false,
    supportsSmallForm: true,
  },
  {
    id: "o",
    kana: "お",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/o.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: false,
    supportsHandakuten: false,
    supportsSmallForm: true,
  },
  {
    id: "ka",
    kana: "か",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/ka.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "ki",
    kana: "き",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/ki.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "ku",
    kana: "く",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/ku.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "ke",
    kana: "け",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/ke.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "ko",
    kana: "こ",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/ko.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "sa",
    kana: "さ",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/sa.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "shi",
    kana: "し",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/shi.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "su",
    kana: "す",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/su.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "se",
    kana: "せ",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/se.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "so",
    kana: "そ",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/so.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "ta",
    kana: "た",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/ta.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "chi",
    kana: "ち",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/chi.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "tsu",
    kana: "つ",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/tsu.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: true,
  },
  {
    id: "te",
    kana: "て",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/te.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  {
    id: "to",
    kana: "と",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/to.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: true,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
  ...(
    [
      ["na", "な", false, false, false],
      ["ni", "に", false, false, false],
      ["nu", "ぬ", false, false, false],
      ["ne", "ね", false, false, false],
      ["no", "の", false, false, false],
      ["ha", "は", true, true, false],
      ["hi", "ひ", true, true, false],
      ["fu", "ふ", true, true, false],
      ["he", "へ", true, true, false],
      ["ho", "ほ", true, true, false],
      ["ma", "ま", false, false, false],
      ["mi", "み", false, false, false],
      ["mu", "む", false, false, false],
      ["me", "め", false, false, false],
      ["mo", "も", false, false, false],
    ] as const
  ).map(
    ([id, kana, supportsDakuten, supportsHandakuten, supportsSmallForm]) =>
      ({
        id,
        kana,
        direction: "horizontal",
        templatePath: `/glyphs/horizontal/${id}.svg`,
        width: 64,
        height: 64,
        status: "draft",
        supportsDakuten,
        supportsHandakuten,
        supportsSmallForm,
      }) satisfies GlyphTemplateDefinition,
  ),
  ...(
    [
      ["ya", "や", false, false, true],
      ["yu", "ゆ", false, false, true],
      ["yo", "よ", false, false, true],
      ["ra", "ら", false, false, false],
      ["ri", "り", false, false, false],
      ["ru", "る", false, false, false],
      ["re", "れ", false, false, false],
      ["ro", "ろ", false, false, false],
      ["wa", "わ", false, false, false],
      ["wo", "を", false, false, false],
      ["n", "ん", false, false, false],
    ] as const
  ).map(
    ([id, kana, supportsDakuten, supportsHandakuten, supportsSmallForm]) =>
      ({
        id,
        kana,
        direction: "horizontal",
        templatePath: `/glyphs/horizontal/${id}.svg`,
        width: 64,
        height: 64,
        status: "draft",
        supportsDakuten,
        supportsHandakuten,
        supportsSmallForm,
      }) satisfies GlyphTemplateDefinition,
  ),
  {
    id: "long-vowel",
    kana: "ー",
    direction: "horizontal",
    templatePath: "/glyphs/horizontal/long-vowel.svg",
    width: 64,
    height: 64,
    status: "draft",
    supportsDakuten: false,
    supportsHandakuten: false,
    supportsSmallForm: false,
  },
] as const satisfies readonly GlyphTemplateDefinition[];

export function findGlyphByKana(kana: string): GlyphTemplateDefinition | undefined {
  return horizontalGlyphs.find((glyph) => glyph.kana === kana);
}
